services:
  hw-mock:
    image: hw-mock:latest
    platform: linux/arm64  # Target Raspberry Pi (ARM64)
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    command: ["tail", "-f", "/dev/null"]
    #environment:
    #  - DISPLAY=${DISPLAY}   # Forward the host's display
    stdin_open: true  # Keep stdin open for interaction
    tty: true         # Allocate a TTY for interactive Bash      
    volumes:
      - ./Test:/workspace/Test
    networks:
      - app-network
    restart: unless-stopped

  influxdb:
    image: influxdb:latest
    platform: linux/arm64  # Target Raspberry Pi (ARM64)
    ports:
      - "8086:8086"
    volumes:
      - influxdb_config:/etc/influxdb       # Persist configuration
      - influxdb_data:/var/lib/influxdb     # Persist data
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    platform: linux/arm64  # Target Raspberry Pi (ARM64)
    ports:
      - "3000:3000"  # Grafana
    volumes:
      - grafana_config:/etc/grafana         # Persist configuration
      - grafana_data:/var/lib/grafana       # Persist data
    networks:
      - app-network
    depends_on:
      - influxdb

  telegraf:
    image: telegraf:latest
    platform: linux/arm64  # Target Raspberry Pi (ARM64)
    #volumes:
    #  - telegraf_config:/etc/telegraf       # Persist configuration
    #  - ./Telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  raspberry_host_config:
  influxdb_config:
  influxdb_data:
  grafana_config:
  grafana_data:
  telegraf_config:
